exclude: .*
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.3
    # if adding directory handled by clang-format
    # you need to adapt prepare_commit and verify_indentation scripts accordingly
    hooks:
    - id: clang-format
      types_or: [c++, c, c#]

ci:
  autofix_prs: true
  autoupdate_schedule: quarterly
